### ISSUE TITLE
Resource Gathering not working

### ISSUE THREAD

**Issue by billyjbryant** [Penguinz-Media-Group/support-desk#1]
### What is not working
Unable to gather resources such as Wood/Stone, etc.

### Reported by
**In Game Name:** KekXavier 
**Steam ID**: 76561198210775993

**Comment by KekXavier** [comment]
> ### What is not working
> Unable to gather resources such as Wood/Stone, etc.
> 
> ### Reported by
> **In Game Name:** KekXavier
> **Steam ID**: 76561198210775993

https://drive.google.com/file/d/1C9AaezNfxSNRVY8SvAk7pFy4z9oTIq8n/view?usp=sharing

here's a video of my gathering resources problem. I only showed wood gathering there but the same problem with stone ores and stone nodes. And also we included the workaround we figured out but its time consuming

**Comment by kp3nguinz** [comment]
Issue related to ItemDeduction in quests bug. It is supposed to apply to your overall requirement, but apparently is not doing such. Removed deduction as going, and now you pay when you claim.
