### ISSUE TITLE
Improve Word Censorship

### ISSUE THREAD

**Issue by billyjbryant** [Penguinz-Media-Group/support-desk#2]
### Issue
Trolls recently came into the server disturbing users and using profanities in the global chat. Need better methods of censoring chat. 

![image](https://user-images.githubusercontent.com/3013565/114343008-d5e16580-9b11-11eb-9090-ca071801ed73.png)

**Comment by kp3nguinz** [comment]
Existing plugin was muting players... but would not allow for unmute without a map wipe. Re-adding for this wipe, will code up a replacement for next wipe.

**Comment by kp3nguinz** [comment]
Found a different plugin to try for interim: https://umod.org/plugins/ufilter
It has been implemented.

**Comment by kp3nguinz** [comment]
ALso to note, players are banned.
