### ISSUE TITLE
[Feature Request]: User Requested Base NPCs

### ISSUE THREAD

**Issue by billyjbryant** [Penguinz-Media-Group/support-desk#6]
### Description

Provide the ability to request Base NPCs to be general "butler" or item vendor npcs that you can have for your shared base (not the city). Potentially have this be an item that should be purchased through economy (either RP points or scrap). And have different pre-defined NPC varieties to choose from. 

### Which Server needs this feature?
Rust Paradise

### Why is this needed?
Adds additional flair to a base, giving users the option to have an Interactive NPC for their community, either to provide community rules and information, ability to purchase items or gear, etc. 

### What is the biggest benefit the server will get from this new feature?
Extra unique value

### Priority

Low

### Your User Details

* User Name: BillyJBryant
* Steam ID: 76561197981571928 
* May we contact you in-game? Yes

**Comment by kp3nguinz** [comment]
This is doable with npc-tp, but nedd to work out logistics
